language: python

python:
  - "3.10"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source=django_mfa  test_runner.py test

after_success:
  coveralls
